#!/usr/bin/env node
/**
 * Regenerates the roadmap tracking issue from the current state of the issue list.
 *
 * Run by .github/workflows/roadmap.yml on every issue event. Issues are grouped by
 * their milestone label (M0-M9, defined in plan.json), so a newly created issue lands
 * in the right section automatically as soon as it is labelled, and closing an issue
 * ticks its box.
 *
 * The rendered body is deterministic — no timestamps, no run ids. That matters: the
 * script only PATCHes when the body actually changed, so an edit cannot trigger an
 * event that triggers another edit.
 *
 * Usage:
 *   node tools/roadmap/update-roadmap.mjs              update the live roadmap issue
 *   node tools/roadmap/update-roadmap.mjs --dry-run    render to stdout, change nothing
 *   node tools/roadmap/update-roadmap.mjs --render f    render from a JSON fixture
 *
 * Env: GITHUB_TOKEN, GITHUB_REPOSITORY (owner/repo), optionally TRIGGERING_ISSUE.
 */

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const PLAN = JSON.parse(readFileSync(resolve(HERE, 'plan.json'), 'utf8'));
const MARKER = '<!-- ROADMAP:AUTOGENERATED -->';

/* ---------------------------------------------------------------- rendering */

function bar(done, total, width) {
  if (total === 0) return '─'.repeat(width);
  let filled = Math.round((done / total) * width);
  if (done > 0 && filled === 0) filled = 1;
  if (done < total && filled === width) filled = width - 1;
  return '█'.repeat(filled) + '░'.repeat(width - filled);
}

/** Strip the "[M3] " prefix — the section heading already says which milestone. */
function cleanTitle(title) {
  return title.replace(/^\s*\[M\d\]\s*/, '').trim();
}

/**
 * Mirror GitHub's heading-anchor algorithm: lowercase, drop everything that is not
 * word/space/hyphen, then spaces to hyphens. Punctuation leaves its surrounding spaces
 * behind, so "M5 — Floors 1 & 2" anchors as "m5--floors-1--2" — collapsing those runs
 * would silently break the link.
 */
function slug(heading) {
  return heading
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s/g, '-');
}

function milestoneOf(issue) {
  const ids = new Set(PLAN.milestones.map((m) => m.id));
  for (const label of issue.labels) if (ids.has(label)) return label;
  return null;
}

function line(issue) {
  const box = issue.state === 'closed' ? 'x' : ' ';
  const epic = issue.labels.includes('epic') ? ' _(epic)_' : '';
  return `- [${box}] #${issue.number} ${cleanTitle(issue.title)}${epic}`;
}

export function renderBody(issues, plan = PLAN) {
  const tracked = issues.filter((i) => !i.labels.includes(plan.roadmapLabel));
  const byNumber = new Map(tracked.map((i) => [i.number, i]));
  const open = (i) => i.state !== 'closed';

  const groups = new Map(plan.milestones.map((m) => [m.id, []]));
  const triage = [];
  for (const issue of tracked) {
    const id = milestoneOf(issue);
    if (id) groups.get(id).push(issue);
    else triage.push(issue);
  }
  for (const list of groups.values()) list.sort((a, b) => a.number - b.number);
  triage.sort((a, b) => a.number - b.number);

  const doneAll = tracked.filter((i) => !open(i)).length;
  const out = [];

  out.push(MARKER);
  out.push(
    '**Live status of the Kellerbier build.** Regenerated automatically whenever an issue is ' +
      'opened, closed, reopened or relabelled — see [How this works](#how-this-works) at the bottom. ' +
      'Do not edit by hand; edits are overwritten on the next issue event.',
  );
  out.push('');
  out.push(`\`${bar(doneAll, tracked.length, 28)}\`  **${doneAll} of ${tracked.length} issues closed**`);
  out.push('');

  /* summary table */
  out.push('| | Milestone | Progress | | Exit criterion |');
  out.push('|---|---|---|---|---|');
  for (const m of plan.milestones) {
    const list = groups.get(m.id);
    const done = list.filter((i) => !open(i)).length;
    const state = list.length === 0 ? '·' : done === list.length ? '✅' : done > 0 ? '🔨' : '·';
    out.push(
      `| ${state} | **[${m.id}](#${slug(`${m.id} — ${m.name}`)}) ${m.name}** | \`${bar(done, list.length, 14)}\` | ${done}/${list.length} | ${m.exit.replace(/\*\*/g, '')} |`,
    );
  }
  out.push('');

  /* next up */
  const nextCritical = plan.criticalPath
    .map((n) => byNumber.get(n))
    .filter((i) => i && open(i));

  out.push('## Next up');
  out.push('');
  if (nextCritical.length > 0) {
    out.push(plan.criticalPathNote);
    out.push('');
    for (const issue of nextCritical) out.push(line(issue));
    out.push('');
  } else {
    out.push('Critical path complete — the game is playable and the question is answerable. 🍺');
    out.push('');
  }

  const active = plan.milestones.find((m) => {
    const list = groups.get(m.id);
    return list.length > 0 && list.some(open);
  });
  if (active) {
    const remaining = groups
      .get(active.id)
      .filter(open)
      .filter((i) => !nextCritical.includes(i))
      .slice(0, 6);
    if (remaining.length > 0) {
      out.push(`Also open in the current milestone, **${active.id} — ${active.name}**:`);
      out.push('');
      for (const issue of remaining) out.push(line(issue));
      out.push('');
    }
  }

  /* milestones */
  out.push('## Milestones');
  out.push('');
  for (const m of plan.milestones) {
    const list = groups.get(m.id);
    const done = list.filter((i) => !open(i)).length;
    out.push(`### ${m.id} — ${m.name}`);
    out.push('');
    out.push(`\`${bar(done, list.length, 20)}\`  ${done}/${list.length}`);
    out.push('');
    out.push(`> **Exit:** ${m.exit}`);
    out.push('');
    if (list.length === 0) out.push('_No issues yet._');
    else for (const issue of list) out.push(line(issue));
    out.push('');
  }

  /* triage */
  if (triage.length > 0) {
    out.push('## Needs triage');
    out.push('');
    out.push(
      'These have no milestone label, so they have nowhere to sit. Add an `M0`–`M9` label and ' +
        'they move into the right section on the next event.',
    );
    out.push('');
    for (const issue of triage) out.push(line(issue));
    out.push('');
  }

  /* footer */
  out.push('---');
  out.push('');
  out.push('## How this works');
  out.push('');
  out.push(
    '`.github/workflows/roadmap.yml` runs `tools/roadmap/update-roadmap.mjs` whenever an issue is ' +
      'opened, closed, reopened, edited or relabelled, and regenerates this body from the live issue list.',
  );
  out.push('');
  out.push('- **Closing an issue** ticks its box and advances its milestone bar.');
  out.push(
    '- **Opening an issue** adds it automatically — label it `M0`–`M9` to place it in a milestone, ' +
      'or it appears under **Needs triage** until you do.',
  );
  out.push('- **Relabelling** an issue moves it between milestones.');
  out.push(
    '- Milestone names, exit criteria and the critical path live in `tools/roadmap/plan.json`. ' +
      'Edit that file to change the shape of this page.',
  );
  out.push(
    '- The rendered body is deterministic and is only written when it actually changed, so this ' +
      'issue cannot edit-loop on itself.',
  );
  out.push('');
  out.push('Run `node tools/roadmap/update-roadmap.mjs --dry-run` to preview locally.');

  return out.join('\n');
}

/* ------------------------------------------------------------------- github */

async function api(path, options = {}) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error('GITHUB_TOKEN is not set');
  const res = await fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      accept: 'application/vnd.github+json',
      authorization: `Bearer ${token}`,
      'x-github-api-version': '2022-11-28',
      'content-type': 'application/json',
      ...options.headers,
    },
  });
  if (!res.ok) throw new Error(`${options.method ?? 'GET'} ${path} → ${res.status} ${await res.text()}`);
  return res.status === 204 ? null : res.json();
}

async function fetchIssues(repo) {
  const all = [];
  for (let page = 1; ; page += 1) {
    const batch = await api(`/repos/${repo}/issues?state=all&per_page=100&page=${page}`);
    all.push(...batch);
    if (batch.length < 100) break;
  }
  return all
    .filter((i) => !i.pull_request)
    .map((i) => ({
      number: i.number,
      title: i.title,
      state: i.state,
      labels: i.labels.map((l) => (typeof l === 'string' ? l : l.name)),
    }));
}

/* --------------------------------------------------------------------- main */

const args = process.argv.slice(2);
const renderIdx = args.indexOf('--render');

if (renderIdx !== -1) {
  const fixture = JSON.parse(readFileSync(args[renderIdx + 1], 'utf8'));
  process.stdout.write(renderBody(fixture));
} else {
  const repo = process.env.GITHUB_REPOSITORY;
  if (!repo) throw new Error('GITHUB_REPOSITORY is not set');

  const issues = await fetchIssues(repo);
  const roadmap = issues
    .filter((i) => i.labels.includes(PLAN.roadmapLabel) && i.state === 'open')
    .sort((a, b) => a.number - b.number)[0];

  if (!roadmap) {
    console.error(
      `No open issue labelled "${PLAN.roadmapLabel}" — create one and the next event will populate it.`,
    );
    process.exit(0);
  }

  // Guard: an edit we make must never be the thing that triggers the next run.
  if (process.env.TRIGGERING_ISSUE === String(roadmap.number)) {
    console.log(`Triggered by the roadmap issue itself (#${roadmap.number}); nothing to do.`);
    process.exit(0);
  }

  const body = renderBody(issues);

  if (args.includes('--dry-run')) {
    process.stdout.write(body);
    process.exit(0);
  }

  const current = await api(`/repos/${repo}/issues/${roadmap.number}`);
  if ((current.body ?? '').trim() === body.trim()) {
    console.log(`Roadmap #${roadmap.number} already current; no write.`);
    process.exit(0);
  }

  await api(`/repos/${repo}/issues/${roadmap.number}`, {
    method: 'PATCH',
    body: JSON.stringify({ body }),
  });
  console.log(`Updated roadmap #${roadmap.number}.`);
}
