// Finds where Alois's hat is in every frame of every body strip, so a hat item's own sprite
// (`ItemDefinition.hat`) can be drawn over exactly that spot: `node tools/art/hat-anchors.mjs`
// rewrites src/render/hat-anchors.ts; `tests/art/hat-anchors.test.ts` fails when it goes stale.
import { readFileSync, writeFileSync } from 'node:fs';
import { PNG } from 'pngjs';
import { format, resolveConfig } from 'prettier';

const DIR = 'assets/sprites/common/characters/';
const FACINGS = ['south', 'north', 'side'];
const FRAME = 32;
/** Hat felt and its shade. */
const HAT_COLOURS = new Set(['d92b3c', 'b6212f']);
const FEATHER = 'f5f0e6';
/** The feather counts only this close to the top of the felt, so a pale sock never does. */
const FEATHER_REACH = 4;
/** The felt is never taller than this, so a red mouth or tongue below it is not hat. */
const HAT_HEIGHT = 9;

/** [centreX, bottom] per frame: hat bounding box (outline included), centre column and the row under its lowest pixel. */
export function computeHatAnchors() {
  const anchors = {};
  for (const drunk of [false, true]) {
    for (const facing of FACINGS) {
      const key = `${drunk ? 'drunk-' : ''}${facing}`;
      const png = PNG.sync.read(readFileSync(`${DIR}alois-${key}.strip.png`));
      const frames = JSON.parse(readFileSync(`${DIR}alois-${key}.anim.json`, 'utf8')).frames;
      const fw = png.width / frames;
      const rows = [];
      for (let f = 0; f < frames; f++) {
        const at = (x, y) => {
          const i = (y * png.width + f * fw + x) * 4;
          return png.data[i + 3] === 0
            ? null
            : [png.data[i], png.data[i + 1], png.data[i + 2]]
                .map((v) => v.toString(16).padStart(2, '0'))
                .join('');
        };
        let top = FRAME;
        for (let y = 0; y < FRAME; y++)
          for (let x = 0; x < fw; x++) if (HAT_COLOURS.has(at(x, y))) top = Math.min(top, y);
        let x0 = fw;
        let x1 = -1;
        let y1 = -1;
        for (let y = 0; y < FRAME; y++) {
          for (let x = 0; x < fw; x++) {
            const c = at(x, y);
            if (
              (HAT_COLOURS.has(c) && y <= top + HAT_HEIGHT) ||
              (c === FEATHER && y <= top + FEATHER_REACH)
            ) {
              x0 = Math.min(x0, x);
              x1 = Math.max(x1, x);
              y1 = Math.max(y1, y);
            }
          }
        }
        rows.push(x1 < 0 ? [fw / 2, 8] : [Math.round((x0 + x1 + 1) / 2), Math.min(FRAME, y1 + 2)]);
      }
      anchors[key] = rows;
    }
  }
  return anchors;
}

/** The generated file's text, formatted the way `npm run lint` wants it (so a regenerate is never a lint diff). */
export async function renderHatAnchorsFile(anchors) {
  const path = 'src/render/hat-anchors.ts';
  return format(renderHatAnchors(anchors), { ...(await resolveConfig(path)), filepath: path });
}

export function renderHatAnchors(anchors) {
  const lines = Object.entries(anchors).map(
    ([key, rows]) => `  '${key}': [${rows.map((r) => `[${r[0]}, ${r[1]}]`).join(', ')}],`,
  );
  return `// Generated by tools/art/hat-anchors.mjs — do not edit by hand.
/**
 * Where Alois's own hat sits in each frame of each body strip: [centre column, row under the
 * hat], in the strip's own frame pixels (20×32) counted from the top-left. A hat item's sprite is
 * drawn with its bottom-centre on this point (\`PlayerView\`).
 */
export const HAT_ANCHORS: Readonly<Record<string, readonly (readonly [number, number])[]>> = {
${lines.join('\n')}
};
`;
}

if (process.argv[1]?.endsWith('hat-anchors.mjs')) {
  writeFileSync('src/render/hat-anchors.ts', await renderHatAnchorsFile(computeHatAnchors()));
}
