// Cuts the Müll item's four pieces of rubbish out of the pixel-bench picks Tilo chose
// (tools/art/authoring/picks/litter-*.png) and writes them as the 14×14 pixel arrays
// `src/render/litter-art.ts` draws: `node tools/art/litter-pixels.mjs` rewrites
// `src/render/litter-pixels.ts`; `tests/art/litter-pixels.test.ts` fails when it goes stale.
import { readFileSync, writeFileSync } from 'node:fs';
import { format, resolveConfig } from 'prettier';
import { decodePng } from './png.mjs';

export const LITTER_SIDE = 14;
const PIECES = ['banana', 'nail', 'apple', 'paper'];

function piece(name) {
  const { width, height, pixels } = decodePng(
    readFileSync(new URL(`./authoring/picks/litter-${name}.png`, import.meta.url)),
  );
  let x0 = width,
    y0 = height,
    x1 = -1,
    y1 = -1;
  for (let y = 0; y < height; y++)
    for (let x = 0; x < width; x++)
      if (pixels[(y * width + x) * 4 + 3] > 0) {
        x0 = Math.min(x0, x);
        x1 = Math.max(x1, x);
        y0 = Math.min(y0, y);
        y1 = Math.max(y1, y);
      }
  const bw = x1 - x0 + 1;
  const bh = y1 - y0 + 1;
  // 12×12 inside the canvas, so the ink edge fits.
  const fit = LITTER_SIDE - 2;
  const scale = Math.min(fit / bw, fit / bh);
  const tw = Math.max(1, Math.round(bw * scale));
  const th = Math.max(1, Math.round(bh * scale));
  const out = new Array(LITTER_SIDE * LITTER_SIDE).fill(-1);
  const ox = Math.floor((LITTER_SIDE - tw) / 2);
  const oy = Math.floor((LITTER_SIDE - th) / 2);
  for (let y = 0; y < th; y++)
    for (let x = 0; x < tw; x++) {
      const sx = x0 + Math.min(bw - 1, Math.floor(x / scale));
      const sy = y0 + Math.min(bh - 1, Math.floor(y / scale));
      const at = (sy * width + sx) * 4;
      if (pixels[at + 3] === 0) continue;
      out[(oy + y) * LITTER_SIDE + ox + x] =
        (pixels[at] << 16) | (pixels[at + 1] << 8) | pixels[at + 2];
    }
  // the hard dark rim
  const inked = [...out];
  for (let y = 0; y < LITTER_SIDE; y++)
    for (let x = 0; x < LITTER_SIDE; x++) {
      if (out[y * LITTER_SIDE + x] >= 0) continue;
      const near = [
        [1, 0],
        [-1, 0],
        [0, 1],
        [0, -1],
      ].some(([dx, dy]) => {
        const nx = x + dx;
        const ny = y + dy;
        return (
          nx >= 0 &&
          ny >= 0 &&
          nx < LITTER_SIDE &&
          ny < LITTER_SIDE &&
          out[ny * LITTER_SIDE + nx] >= 0
        );
      });
      if (near) inked[y * LITTER_SIDE + x] = 0x2a1c12;
    }
  return inked;
}

/** The generated file's text, formatted the way `npm run lint` wants it (so a regenerate is never a lint diff). */
export async function renderLitterPixelsFile() {
  const path = 'src/render/litter-pixels.ts';
  return format(renderLitterPixels(), { ...(await resolveConfig(path)), filepath: path });
}

function renderLitterPixels() {
  const rows = PIECES.map((name) => {
    const px = piece(name);
    const lines = [];
    for (let y = 0; y < LITTER_SIDE; y++) {
      lines.push(
        '    ' +
          px
            .slice(y * LITTER_SIDE, (y + 1) * LITTER_SIDE)
            .map((c) => (c < 0 ? '-1' : `0x${c.toString(16).padStart(6, '0')}`))
            .join(', ') +
          ',',
      );
    }
    return `  // ${name}\n  [\n${lines.join('\n')}\n  ],`;
  });
  return `// Generated by tools/art/litter-pixels.mjs — do not edit by hand.
/**
 * The Müll item's four pieces of rubbish — banana peel, nail, apple core, paper — as 14×14 colours
 * (\`-1\` clear), cut from the pixel-bench picks in tools/art/authoring/picks.
 */
export const LITTER_PIXEL_DATA: readonly (readonly number[])[] = [
${rows.join('\n')}
];
`;
}

if (process.argv[1]?.endsWith('litter-pixels.mjs')) {
  writeFileSync('src/render/litter-pixels.ts', await renderLitterPixelsFile());
}
